name: Publish Pre Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set Git Config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Determine Next Pre-release Version
        id: prerelease-version
        run: |
          CURRENT_VERSION=$(npm view . version)
          # Extract only the numeric part of the pre-release version
          LATEST_PRE=$(npm view . versions --json | jq -r '.[] | select(test("'"$CURRENT_VERSION-pre"'\d+$'))' | sort -V | tail -n1)
          if [ -z "$LATEST_PRE" ]; then
            NEXT_PRE_VERSION="${CURRENT_VERSION}-pre.1"
          else
            PRE_NUM=$(echo $LATEST_PRE | awk -F "-pre." '{print $2}')
            NEXT_PRE_VERSION="${CURRENT_VERSION}-pre.$((PRE_NUM+1))
          fi
          echo "NEXT_PRE_VERSION=$NEXT_PRE_VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$NEXT_PRE_VERSION"

      - name: Publish to npm
        run: npm version ${{ steps.prerelease-version.outputs.version }} && npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
